/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\thunderlist.theme.ts
 * Command: astryx theme build src\theme\thunderlist.theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/**
 * thunderlist theme — built by `bunx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { thunderlistTheme } from './thunderlist';
 *   import './thunderlist.css';
 */
export const thunderlistTheme = {
  name: 'thunderlist',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#1D4ED8, #2563EB)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #FFFFFF)",
    "--color-neutral": "light-dark(#1C1B211A, #E1E2EC33)",
    "--color-background-surface": "light-dark(#FCFCFF, #1A1B22)",
    "--color-background-body": "light-dark(#F1F0F9, #0F1018)",
    "--color-overlay": "light-dark(#1C1B2166, #1A1B2299)",
    "--color-overlay-hover": "light-dark(#1C1B210D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1C1B211A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1C1B210D, #1A1B2280)",
    "--color-text-primary": "light-dark(#1C1B21, #E1E2EC)",
    "--color-text-secondary": "light-dark(#474552, #A8AAB9)",
    "--color-text-disabled": "light-dark(#918F9D, #5B5E6B)",
    "--color-text-accent": "light-dark(#1D4ED8, #7FBBFF)",
    "--color-icon-accent": "light-dark(#1D4ED8, #7FBBFF)",
    "--color-icon-primary": "light-dark(#1C1B21, #E1E2EC)",
    "--color-icon-secondary": "light-dark(#474552, #A8AAB9)",
    "--color-icon-disabled": "light-dark(#918F9D, #5B5E6B)",
    "--color-background-card": "light-dark(#FCFCFF, #1A1B22)",
    "--color-background-popover": "light-dark(#FCFCFF, #2F3037)",
    "--color-background-inverted": "light-dark(#1C1B21, #FBFCFF)",
    "--color-border": "light-dark(#1C1B211A, #EFF0FA1A)",
    "--color-border-emphasized": "light-dark(#918F9D, #656775)",
    "--color-skeleton": "light-dark(#ACAAB8, #444653)",
    "--color-track": "light-dark(#ACAAB8, #444653)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--radius-none": "0px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--radius-chat": "42px",
    "--radius-full": "9999px"
  },
  components: {
    "progressbar-track": {
      "base": {
        "backgroundColor": "var(--color-track)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
