/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\thunderlist.theme.ts
 * Command: astryx theme build src\theme\thunderlist.theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const thunderlistTheme: DefinedTheme;
