import * as v from "valibot";

/**
 * Ids are generated by the app and travel in URLs and query keys, so the shape
 * stays permissive while still excluding anything awkward to round-trip.
 */
export const idSchema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(1, "Id is required"),
	v.maxLength(64, "Id is too long"),
	v.regex(/^[A-Za-z0-9_-]+$/, "Id contains unsupported characters"),
);

/** No upper limit: a title is as long as whoever writes it needs it to be. */
export const titleSchema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(1, "Title is required"),
);

export const descriptionSchema = v.pipe(
	v.string(),
	v.trim(),
	v.maxLength(500, "Description must be 500 characters or fewer"),
);

export const noteSchema = v.pipe(
	v.string(),
	v.trim(),
	v.maxLength(500, "Note must be 500 characters or fewer"),
);

/** A calendar day with no timezone, e.g. `2026-09-07`. */
export const dateOnlySchema = v.pipe(
	v.string(),
	v.isoDate("Use a YYYY-MM-DD date"),
);

/** Empty string is treated as "no url" so a cleared form field round-trips. */
export const optionalUrlSchema = v.pipe(
	v.nullable(
		v.union([v.literal(""), v.pipe(v.string(), v.url("Enter a valid URL"))]),
	),
	v.transform((value) => (value === "" ? null : value)),
);

/**
 * Sibling ordering. Kept as a plain number so gaps (10, 20, 30) can be used to
 * insert between two entries without renumbering the whole list.
 */
export const sortOrderSchema = v.pipe(
	v.number(),
	v.finite("Sort order must be a number"),
	v.minValue(0, "Sort order cannot be negative"),
	v.maxValue(1_000_000_000, "Sort order is too large"),
);

export const directionSchema = v.picklist(["up", "down"] as const);

/** Today as `YYYY-MM-DD` in the viewer's own timezone, not UTC. */
export function todayDateOnly(now: Date = new Date()): string {
	const year = now.getFullYear();
	const month = String(now.getMonth() + 1).padStart(2, "0");
	const day = String(now.getDate()).padStart(2, "0");
	return `${year}-${month}-${day}`;
}
