import * as v from "valibot";

/**
 * Ids are generated by the app and travel in URLs and query keys, so the shape
 * stays permissive while still excluding anything awkward to round-trip.
 */
export const idSchema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(1, "Id is required"),
	v.maxLength(64, "Id is too long"),
	v.regex(/^[A-Za-z0-9_-]+$/, "Id contains unsupported characters"),
);

/**
 * Tag ids carried by a task, a checklist or a tracker, in the order the user
 * applied them.
 */
export const tagIdsSchema = v.pipe(
	v.array(idSchema),
	v.maxLength(20, "At most 20 tags can be applied"),
);

/** No upper limit: a title is as long as whoever writes it needs it to be. */
export const titleSchema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(1, "Title is required"),
);

export const descriptionSchema = v.pipe(
	v.string(),
	v.trim(),
	v.maxLength(500, "Description must be 500 characters or fewer"),
);

export const noteSchema = v.pipe(
	v.string(),
	v.trim(),
	v.maxLength(500, "Note must be 500 characters or fewer"),
);

/** A calendar day with no timezone, e.g. `2026-09-07`. */
export const dateOnlySchema = v.pipe(
	v.string(),
	v.isoDate("Use a YYYY-MM-DD date"),
);

/** A time of day with no timezone, e.g. `18:30`: the viewer's own clock. */
export const timeOfDaySchema = v.pipe(
	v.string(),
	v.regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Use an HH:MM time"),
);

/**
 * The hours of every day something is worked in, e.g. `06:00` to `22:00`.
 *
 * Something paced to one is measured against today's stretch of it — each day
 * afresh — instead of against a deadline. It has to end after it starts: a
 * window across midnight would belong to two days at once.
 */
export const dailyWindowSchema = v.pipe(
	v.object({ from: timeOfDaySchema, to: timeOfDaySchema }),
	v.check(
		(window) => window.to > window.from,
		"The window has to end after it starts",
	),
);

export type DailyWindow = v.InferOutput<typeof dailyWindowSchema>;

/** The window a daily schedule starts with: morning to night. */
export const DEFAULT_DAILY_WINDOW: DailyWindow = { from: "06:00", to: "22:00" };

/** Empty string is treated as "no url" so a cleared form field round-trips. */
export const optionalUrlSchema = v.pipe(
	v.nullable(
		v.union([v.literal(""), v.pipe(v.string(), v.url("Enter a valid URL"))]),
	),
	v.transform((value) => (value === "" ? null : value)),
);

/** Today as `YYYY-MM-DD` in the viewer's own timezone, not UTC. */
export function todayDateOnly(now: Date = new Date()): string {
	const year = now.getFullYear();
	const month = String(now.getMonth() + 1).padStart(2, "0");
	const day = String(now.getDate()).padStart(2, "0");
	return `${year}-${month}-${day}`;
}
