/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as CountdownsRouteImport } from './routes/countdowns'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiNotifyRouteImport } from './routes/api/notify'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ChecklistsIndexRouteImport } from './routes/checklists.index'
import { Route as ChecklistsChecklistIdRouteImport } from './routes/checklists.$checklistId'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsTagIdRouteImport } from './routes/tags.$tagId'
import { Route as TagsUntaggedRouteImport } from './routes/tags.untagged'
import { Route as TrackersIndexRouteImport } from './routes/trackers.index'
import { Route as TrackersTrackerIdRouteImport } from './routes/trackers.$trackerId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownsRoute = CountdownsRouteImport.update({
  id: '/countdowns',
  path: '/countdowns',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIndexRoute = ChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsChecklistIdRoute = ChecklistsChecklistIdRouteImport.update({
  id: '/checklists/$checklistId',
  path: '/checklists/$checklistId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsUntaggedRoute = TagsUntaggedRouteImport.update({
  id: '/tags/untagged',
  path: '/tags/untagged',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersIndexRoute = TrackersIndexRouteImport.update({
  id: '/trackers/',
  path: '/trackers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersTrackerIdRoute = TrackersTrackerIdRouteImport.update({
  id: '/trackers/$trackerId',
  path: '/trackers/$trackerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/countdowns': typeof CountdownsRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/settings': typeof SettingsRoute
  '/stages': typeof StagesRoute
  '/today': typeof TodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/version': typeof ApiVersionRoute
  '/checklists/$checklistId': typeof ChecklistsChecklistIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/untagged': typeof TagsUntaggedRoute
  '/trackers/$trackerId': typeof TrackersTrackerIdRoute
  '/checklists/': typeof ChecklistsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/countdowns': typeof CountdownsRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/settings': typeof SettingsRoute
  '/stages': typeof StagesRoute
  '/today': typeof TodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/version': typeof ApiVersionRoute
  '/checklists/$checklistId': typeof ChecklistsChecklistIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/untagged': typeof TagsUntaggedRoute
  '/trackers/$trackerId': typeof TrackersTrackerIdRoute
  '/checklists': typeof ChecklistsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/plans': typeof PlansIndexRoute
  '/tags': typeof TagsIndexRoute
  '/trackers': typeof TrackersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/countdowns': typeof CountdownsRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/settings': typeof SettingsRoute
  '/stages': typeof StagesRoute
  '/today': typeof TodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/notify': typeof ApiNotifyRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/version': typeof ApiVersionRoute
  '/checklists/$checklistId': typeof ChecklistsChecklistIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/untagged': typeof TagsUntaggedRoute
  '/trackers/$trackerId': typeof TrackersTrackerIdRoute
  '/checklists/': typeof ChecklistsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/countdowns'
    | '/login'
    | '/priority'
    | '/settings'
    | '/stages'
    | '/today'
    | '/api/mcp'
    | '/api/notify'
    | '/api/uploadthing'
    | '/api/version'
    | '/checklists/$checklistId'
    | '/groups/$groupId'
    | '/plans/$planId'
    | '/tags/$tagId'
    | '/tags/untagged'
    | '/trackers/$trackerId'
    | '/checklists/'
    | '/groups/'
    | '/plans/'
    | '/tags/'
    | '/trackers/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/countdowns'
    | '/login'
    | '/priority'
    | '/settings'
    | '/stages'
    | '/today'
    | '/api/mcp'
    | '/api/notify'
    | '/api/uploadthing'
    | '/api/version'
    | '/checklists/$checklistId'
    | '/groups/$groupId'
    | '/plans/$planId'
    | '/tags/$tagId'
    | '/tags/untagged'
    | '/trackers/$trackerId'
    | '/checklists'
    | '/groups'
    | '/plans'
    | '/tags'
    | '/trackers'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/countdowns'
    | '/login'
    | '/priority'
    | '/settings'
    | '/stages'
    | '/today'
    | '/api/mcp'
    | '/api/notify'
    | '/api/uploadthing'
    | '/api/version'
    | '/checklists/$checklistId'
    | '/groups/$groupId'
    | '/plans/$planId'
    | '/tags/$tagId'
    | '/tags/untagged'
    | '/trackers/$trackerId'
    | '/checklists/'
    | '/groups/'
    | '/plans/'
    | '/tags/'
    | '/trackers/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRoute
  CountdownsRoute: typeof CountdownsRoute
  LoginRoute: typeof LoginRoute
  PriorityRoute: typeof PriorityRoute
  SettingsRoute: typeof SettingsRoute
  StagesRoute: typeof StagesRoute
  TodayRoute: typeof TodayRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiNotifyRoute: typeof ApiNotifyRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ChecklistsChecklistIdRoute: typeof ChecklistsChecklistIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  TagsUntaggedRoute: typeof TagsUntaggedRoute
  TrackersTrackerIdRoute: typeof TrackersTrackerIdRoute
  ChecklistsIndexRoute: typeof ChecklistsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  TrackersIndexRoute: typeof TrackersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdowns': {
      id: '/countdowns'
      path: '/countdowns'
      fullPath: '/countdowns'
      preLoaderRoute: typeof CountdownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/': {
      id: '/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof ChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$checklistId': {
      id: '/checklists/$checklistId'
      path: '/checklists/$checklistId'
      fullPath: '/checklists/$checklistId'
      preLoaderRoute: typeof ChecklistsChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/untagged': {
      id: '/tags/untagged'
      path: '/tags/untagged'
      fullPath: '/tags/untagged'
      preLoaderRoute: typeof TagsUntaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/': {
      id: '/trackers/'
      path: '/trackers'
      fullPath: '/trackers/'
      preLoaderRoute: typeof TrackersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/$trackerId': {
      id: '/trackers/$trackerId'
      path: '/trackers/$trackerId'
      fullPath: '/trackers/$trackerId'
      preLoaderRoute: typeof TrackersTrackerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRoute,
  CountdownsRoute: CountdownsRoute,
  LoginRoute: LoginRoute,
  PriorityRoute: PriorityRoute,
  SettingsRoute: SettingsRoute,
  StagesRoute: StagesRoute,
  TodayRoute: TodayRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiNotifyRoute: ApiNotifyRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiVersionRoute: ApiVersionRoute,
  ChecklistsChecklistIdRoute: ChecklistsChecklistIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  TagsUntaggedRoute: TagsUntaggedRoute,
  TrackersTrackerIdRoute: TrackersTrackerIdRoute,
  ChecklistsIndexRoute: ChecklistsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  TrackersIndexRoute: TrackersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
